name: 0.5.0

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: 0.5.0
      run: docker build -f Dockerfile -t coolbeevip/servicecomb-pack .
