name: 0.6.0 All-in-One

on:
  push:
    paths:
      - "0.6.0/Dockerfile.allinone"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./0.6.0
      run: docker build -f Dockerfile.allinone -t coolbeevip/servicecomb-pack-allinone .
