name: Apache ServiceComb Pack 0.6.0 All-in-One

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -f 0.6.0/Dockerfile.allinone -t coolbeevip/servicecomb-pack-allinone .
