name: 0.7.0-all-in-one

on:
  push:
    paths:
      - "0.7.0-all-in-one/Dockerfile"
      - ".github/workflows/0.7.0-all-in-one.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./0.7.0-all-in-one
          file: ./0.7.0-all-in-one/Dockerfile.all-in-one
          push: true
          tags: coolbeevip/servicecomb-pack:0.7.0-all-in-one,coolbeevip/servicecomb-pack:latest-all-in-one
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
